// Generated by delombok at Mon Mar 05 18:34:50 PST 2012
package org.opendatakit.aggregate.odktables.api.client;

import javax.ws.rs.core.UriBuilder;
import com.sun.jersey.api.client.ClientHandlerException;
import com.sun.jersey.api.client.ClientRequest;
import com.sun.jersey.api.client.ClientResponse;
import com.sun.jersey.api.client.filter.ClientFilter;

public class AccessTokenFilter extends ClientFilter {
	private final String accessToken;
	
	@Override
	public ClientResponse handle(ClientRequest cr) throws ClientHandlerException {
		// Modify the request
		ClientRequest mcr = modifyRequest(cr);
		// Call the next client handler in the filter chain
		ClientResponse resp = getNext().handle(mcr);
		// Modify the response
		return resp;
	}
	
	public ClientRequest modifyRequest(ClientRequest cr) {
		UriBuilder ub = UriBuilder.fromUri(cr.getURI());
		ub.queryParam("access_token", accessToken);
		cr.setURI(ub.build());
		return cr;
	}
	
	@java.beans.ConstructorProperties({"accessToken"})
	@java.lang.SuppressWarnings("all")
	public AccessTokenFilter(final String accessToken) {
		this.accessToken = accessToken;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getAccessToken() {
		return this.accessToken;
	}
}