// Generated by delombok at Mon Mar 05 18:34:50 PST 2012
package org.opendatakit.aggregate.odktables.api.impl;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import javax.ws.rs.core.UriBuilder;
import javax.ws.rs.core.UriInfo;
import org.opendatakit.aggregate.odktables.DataManager;
import org.opendatakit.aggregate.odktables.api.DataService;
import org.opendatakit.aggregate.odktables.api.TableService;
import org.opendatakit.aggregate.odktables.api.entity.RowResource;
import org.opendatakit.aggregate.odktables.entity.Row;
import org.opendatakit.aggregate.odktables.exception.RowVersionMismatchException;
import org.opendatakit.common.persistence.exception.ODKDatastoreException;
import org.opendatakit.common.persistence.exception.ODKEntityNotFoundException;
import org.opendatakit.common.persistence.exception.ODKTaskLockException;
import org.opendatakit.common.web.CallingContext;

public class DataServiceImpl implements DataService {
	private DataManager dm;
	private UriInfo info;
	
	public DataServiceImpl(String tableId, UriInfo info, CallingContext cc) throws ODKEntityNotFoundException, ODKDatastoreException {
		this.dm = new DataManager(tableId, cc);
		this.info = info;
	}
	
	@Override
	public List<RowResource> getRows() throws ODKDatastoreException {
		final java.util.List<org.opendatakit.aggregate.odktables.entity.Row> rows = dm.getRows();
		final java.util.ArrayList<org.opendatakit.aggregate.odktables.api.entity.RowResource> resources = new ArrayList<RowResource>();
		for (final org.opendatakit.aggregate.odktables.entity.Row row : rows) {
			resources.add(getResource(row));
		}
		return resources;
	}
	
	@Override
	public RowResource getRow(String rowId) throws ODKDatastoreException {
		final org.opendatakit.aggregate.odktables.entity.Row row = dm.getRowNullSafe(rowId);
		final org.opendatakit.aggregate.odktables.api.entity.RowResource resource = getResource(row);
		return resource;
	}
	
	@Override
	public RowResource createOrUpdateRow(String rowId, Row row) throws ODKTaskLockException, ODKDatastoreException, RowVersionMismatchException {
		row.setRowId(rowId);
		final org.opendatakit.aggregate.odktables.entity.Row dbRow = dm.getRow(rowId);
		if (dbRow == null) {
			row = dm.insertRow(row);
		} else {
			row = dm.updateRow(row);
		}
		final org.opendatakit.aggregate.odktables.api.entity.RowResource resource = getResource(row);
		return resource;
	}
	
	@Override
	public void deleteRow(String rowId) throws ODKDatastoreException, ODKTaskLockException {
		dm.deleteRow(rowId);
	}
	
	private RowResource getResource(Row row) {
		String tableId = dm.getTableId();
		String rowId = row.getRowId();
		UriBuilder ub = info.getBaseUriBuilder();
		ub.path(TableService.class);
		ub.path(TableService.class, "getData");
		URI self = ub.clone().path(DataService.class, "getRow").build(tableId, rowId);
		URI table = ub.clone().build(tableId);
		RowResource resource = new RowResource(row);
		resource.setSelfUri(self.toASCIIString());
		resource.setTableUri(table.toASCIIString());
		return resource;
	}
}