// Generated by delombok at Mon Mar 05 18:34:50 PST 2012
package org.opendatakit.aggregate.odktables.api.impl;

import java.util.HashSet;
import java.util.Set;
import javax.ws.rs.core.Application;

public class ODKTablesAPIApplication extends Application {
	
	
	@Override
	public Set<Class<?>> getClasses() {
		final java.util.HashSet<java.lang.Class<?>> classes = new HashSet<Class<?>>();
		classes.add(TableServiceImpl.class);
		classes.add(ODKDatastoreExceptionMapper.class);
		classes.add(ODKTablesExceptionMapper.class);
		classes.add(RuntimeExceptionMapper.class);
		return classes;
	}
}