package org.opendatakit.aggregate.odktables.api;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.PathSegment;

/**
 * Servlet for handling the uploading and downloading of files from the phone.
 * <p>
 * The general idea is that the interaction with the actual files will occur at
 * /odktables/files/unrootedPathToFile. Files will thus be referred to by their
 * unrooted path relative to the /odk/tables/ directory on the device.
 * <p>
 * A GET request to that url will download the file. A POST request to that url
 * must contain an entity that is the file, as well as a table id parameter on
 * the POST itself. 
 * <p>
 * These urls should be generated by a file manifest servlet on a table id
 * basis.
 * @author sudar.sam@gmail.com
 *
 */
@Path("/files")
public interface FileService {
  
  public static final String PARAM_AS_ATTACHMENT = "as_attachment";
  public static final String ERROR_MSG_INSUFFICIENT_PATH = 
      "Not Enough Path Segments: must be at least 2.";
  public static final String ERROR_MSG_UNRECOGNIZED_APP_ID =
      "Unrecognized app id: ";
  public static final String MIME_TYPE_IMAGE_JPEG = "image/jpeg";
  
  @GET
  @Path("{filePath:.*}")
  public void getFile(@Context ServletContext servletContext, 
      @PathParam("filePath") List<PathSegment> segments,
      @Context HttpServletRequest req, @Context HttpServletResponse resp)
      throws IOException;
      
  @POST
  @Path("{filePath:.*}")
  public void putFile(@Context ServletContext servletContext,
      @PathParam("filePath") List<PathSegment> segments, 
      @Context HttpServletRequest req, @Context HttpServletResponse resp)
      throws IOException;

}
