#!/bin/sh

PROPS_FILE=/var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/security.properties

rawHostname=$(grep hostname ${PROPS_FILE} | awk '{split($0,a,"="); print a[2]}')
hostname=${rawHostname:-localhost}
httpPort=$(grep port ${PROPS_FILE} | awk '{split($0,a,"="); print a[2]}')
httpsPort=$(grep securePort ${PROPS_FILE} | awk '{split($0,a,"="); print a[2]}')


echo "ODK Aggregate is running at"
if [ ${httpPort} = "80" ]; then
  echo "  - http://${hostname}"
else
  echo "  - http://${hostname}:${httpPort}"
fi
if [ ${httpsPort} = "443" ]; then
  echo "  - https://${hostname}"
else
  echo "  - https://${hostname}:${httpsPort}"
fi
echo ""