// Generated by delombok at Mon Mar 05 18:34:50 PST 2012
package org.opendatakit.aggregate.odktables.entity;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Column {
	private String name;
	private ColumnType type;
	
	public enum ColumnType {
		STRING,
		INTEGER,
		DECIMAL,
		BOOLEAN,
		DATETIME;
		
	}
	
	@java.beans.ConstructorProperties({"name", "type"})
	@java.lang.SuppressWarnings("all")
	public Column(final String name, final ColumnType type) {
		this.name = name;
		this.type = type;
	}
	
	@java.lang.SuppressWarnings("all")
	public Column() {
	}
	
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}
	
	@java.lang.SuppressWarnings("all")
	public ColumnType getType() {
		return this.type;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setType(final ColumnType type) {
		this.type = type;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Column)) return false;
		final Column other = (Column)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getName() == null ? other.getName() != null : !this.getName().equals((java.lang.Object)other.getName())) return false;
		if (this.getType() == null ? other.getType() != null : !this.getType().equals((java.lang.Object)other.getType())) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof Column;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.getName() == null ? 0 : this.getName().hashCode());
		result = result * PRIME + (this.getType() == null ? 0 : this.getType().hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Column(name=" + this.getName() + ", type=" + this.getType() + ")";
	}
}