// Generated by delombok at Mon Mar 05 18:34:50 PST 2012
package org.opendatakit.aggregate.odktables.entity;

import java.util.Map;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Row {
	private String rowId;
	private String rowEtag;
	private String groupOrUserId;
	private boolean deleted;
	private Map<String, String> values;
	/**
   * Construct a row for insertion.
   * 
   * @param rowId
   * @param groupOrUserId
   * @param values
   */
	public static Row forInsert(String rowId, String groupOrUserId, Map<String, String> values) {
		Row row = new Row();
		row.setRowId(rowId);
		row.setGroupOrUserId(groupOrUserId);
		row.setValues(values);
		return row;
	}
	/**
   * Construct a row for updating.
   * 
   * @param rowId
   * @param values
   */
	public static Row forUpdate(String rowId, String rowEtag, Map<String, String> values) {
		Row row = new Row();
		row.setRowId(rowId);
		row.setRowEtag(rowEtag);
		row.setValues(values);
		return row;
	}
	
	@java.lang.SuppressWarnings("all")
	public Row() {
	}
	
	@java.lang.SuppressWarnings("all")
	public String getRowId() {
		return this.rowId;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getRowEtag() {
		return this.rowEtag;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getGroupOrUserId() {
		return this.groupOrUserId;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean isDeleted() {
		return this.deleted;
	}
	
	@java.lang.SuppressWarnings("all")
	public Map<String, String> getValues() {
		return this.values;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setRowId(final String rowId) {
		this.rowId = rowId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setRowEtag(final String rowEtag) {
		this.rowEtag = rowEtag;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setGroupOrUserId(final String groupOrUserId) {
		this.groupOrUserId = groupOrUserId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setDeleted(final boolean deleted) {
		this.deleted = deleted;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setValues(final Map<String, String> values) {
		this.values = values;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Row)) return false;
		final Row other = (Row)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getRowId() == null ? other.getRowId() != null : !this.getRowId().equals((java.lang.Object)other.getRowId())) return false;
		if (this.getRowEtag() == null ? other.getRowEtag() != null : !this.getRowEtag().equals((java.lang.Object)other.getRowEtag())) return false;
		if (this.getGroupOrUserId() == null ? other.getGroupOrUserId() != null : !this.getGroupOrUserId().equals((java.lang.Object)other.getGroupOrUserId())) return false;
		if (this.isDeleted() != other.isDeleted()) return false;
		if (this.getValues() == null ? other.getValues() != null : !this.getValues().equals((java.lang.Object)other.getValues())) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof Row;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.getRowId() == null ? 0 : this.getRowId().hashCode());
		result = result * PRIME + (this.getRowEtag() == null ? 0 : this.getRowEtag().hashCode());
		result = result * PRIME + (this.getGroupOrUserId() == null ? 0 : this.getGroupOrUserId().hashCode());
		result = result * PRIME + (this.isDeleted() ? 1231 : 1237);
		result = result * PRIME + (this.getValues() == null ? 0 : this.getValues().hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Row(rowId=" + this.getRowId() + ", rowEtag=" + this.getRowEtag() + ", groupOrUserId=" + this.getGroupOrUserId() + ", deleted=" + this.isDeleted() + ", values=" + this.getValues() + ")";
	}
}