// Generated by delombok at Mon Mar 05 18:34:50 PST 2012
package org.opendatakit.aggregate.odktables.entity;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class TableEntry {
	private String tableId;
	private String dataEtag;
	
	@java.beans.ConstructorProperties({"tableId", "dataEtag"})
	@java.lang.SuppressWarnings("all")
	public TableEntry(final String tableId, final String dataEtag) {
		this.tableId = tableId;
		this.dataEtag = dataEtag;
	}
	
	@java.lang.SuppressWarnings("all")
	public TableEntry() {
	}
	
	@java.lang.SuppressWarnings("all")
	public String getTableId() {
		return this.tableId;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getDataEtag() {
		return this.dataEtag;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setTableId(final String tableId) {
		this.tableId = tableId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setDataEtag(final String dataEtag) {
		this.dataEtag = dataEtag;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TableEntry)) return false;
		final TableEntry other = (TableEntry)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getTableId() == null ? other.getTableId() != null : !this.getTableId().equals((java.lang.Object)other.getTableId())) return false;
		if (this.getDataEtag() == null ? other.getDataEtag() != null : !this.getDataEtag().equals((java.lang.Object)other.getDataEtag())) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof TableEntry;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.getTableId() == null ? 0 : this.getTableId().hashCode());
		result = result * PRIME + (this.getDataEtag() == null ? 0 : this.getDataEtag().hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "TableEntry(tableId=" + this.getTableId() + ", dataEtag=" + this.getDataEtag() + ")";
	}
}