CREATE USER odk WITH PASSWORD 'odk';
CREATE DATABASE odk WITH OWNER odk;
GRANT ALL PRIVILEGES ON DATABASE odk TO odk;
\c odk;
CREATE SCHEMA aggregate;
GRANT ALL PRIVILEGES ON SCHEMA aggregate TO odk;
